services:
  db-dev:
    image: postgres:16.9-alpine3.22
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-dev:/var/lib/postgresql/data
    networks:
      - freecodecamp

  

volumes:
  db-dev:
    external: false

networks:
  freecodecamp: